### ISSUE TITLE
Mover repositório para Organization spgroup

### ISSUE THREAD

**Issue by leopoldomt** [spgroup/SPL-Classification#11]
Colocar o repositório na organização @spgroup - vou te adicionar lá.

**Comment by matheusraz** [comment]
Eu preciso de permissão para fazer fork do repositório pra dentro da organização do SPG @leopoldomt

**Comment by leopoldomt** [comment]
Oi @matheusraz - não dá pra gente transferir ownership do projeto pra lá? Eu vou te adicionar como parte da Organization - pensei que já tinha adicionado.

**Comment by leopoldomt** [comment]
Se tu me der admin neste repositório aqui, eu não conseguiria jogar pra lá?

**Comment by matheusraz** [comment]
Acabei de transferir a ownership pra ti, acho que agora tu consegue enviar pra lá @leopoldomt

**Comment by leopoldomt** [comment]
Pronto, transferido pra dentro da organização. Me avisa se não conseguir acessar, mas deve estar ok.
